### ISSUE TITLE
Issue when authenticating

### ISSUE THREAD

**Issue by lovenomuch** [fix/grails-alfresco-plugin#1]
Hi Fix,

I've got this weird issue (with your alfresco plugin version 0.6) trying to get a new ticket using: alferscoUsersService.getTicket(servername,user)

The error from the console is: 
The Web Script /alfresco/servicee/cma/authenticationservice has responded with a status of 404 - Not Found

I've noticed that the link has an extra 'e' after '/alfresco/service' not sure what happens there. I have not touched any beans you've initialized in Spring.

I tried to use authenticationService.authenticate("http://10.0.2.31:28080/alfresco/service", user, pwd.toCharArray()) and it works just fine. I am wondering if there is any unicode conversion in the Rivet's CMA package that create the extra 'e' there.

Can you please help?

Regards,
Long

**Comment by fix** [comment]
Hi long,
Yes i recently came accross this bug (ie 2 days ago!) and found that in registering an AlfrescoServer, you should remove the trailing "/" so in your case "http://10.0.2.31:28080" and not "http://10.0.2.31:28080/"

I will try to fix the case. I think this is due to some serialisation problem. Let me know whether this workaround works!

**Comment by fix** [comment]
Long,
Any news?

**Comment by lovenomuch** [comment]
Let me check and get back to you. Thanks for the reply, :).

**Comment by lovenomuch** [comment]
It works great, Fix. Thanks a lot. :)
